<?php
    //$form = new Authentication\Form\AuthenticationForm();
    $form = $this->form;
    
    if(!$form){
        $form = new Authentication\Form\LoginForm();
    }
    
    $form->prepare();
?>

<section id="body">
    <div class="text-center"><h3>Bienvenido a Plataforma de Seguimiento al Estudiante</h3></div>
    <div class="form-small">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Inicio de sesi&oacute;n
            </div>
            <div class="panel-body">
                    <?= $this->form()->openTag($form); ?>                
                <div class="form-group">
                    <?= $this->formRow($form->get('userName')); ?>
                </div>
                <div class="form-group">
                    <?= $this->formRow($form->get('userPassword')); ?>
                </div>
                <br>
                <?= $this->formElement($form->get('sendAuthenticationInformation')); ?>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</section>
