<?php
/*
 * Copyright (c) 2017 Elder Mutzus <elmutzus@gmail.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */
$idSecret = urldecode($this->idSecret);
$form->setAttribute('action',  $this->url('surveyManagementRoute', ['action' => 'addOrUpdateStudentBrother', 'id' => $this->id]). '?idSecret=' . urlencode($idSecret));
$form->prepare();
?>

<section id="body">
    <div class="text-center"><h3>Evaluaci&oacute;n Demogr&aacute;fica</h3></div>
    <div class="panel panel-md panel-primary">
        <div class="panel-heading">
            <div class="text-center">
                <strong>Datos de los(as) hermanos(as)</strong>
            </div>                
        </div>
        <div class="panel-body">
            <?= $this->form()->openTag($form); ?>
            <div class="form-group">
                <?= $this->formElement($form->get('studentId')); ?>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="row">
                    <div class="col-sm-3 col-md-3 col-lg-3">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('quantity')); ?>
                            <?= $this->formElement($form->get('quantity')); ?>
                            <?= $this->formElementErrors($form->get('quantity'), ['class' => 'alert-danger']); ?>
                        </div>
                    </div>            
                    <div class="col-sm-9 col-md-9 col-lg-9">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('place')); ?>
                            <?= $this->formElement($form->get('place')); ?>
                            <?= $this->formElementErrors($form->get('place'), ['class' => 'alert-danger']); ?>
                        </div>
                    </div>                    
                </div>
            </div>            
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="form-group">
                    <?= $this->formLabel($form->get('academicTitle')); ?>
                    <?= $this->formElement($form->get('academicTitle')); ?>
                    <?= $this->formElementErrors($form->get('academicTitle'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="form-group">
                    <?= $this->formLabel($form->get('communication')); ?>
                    <?= $this->formElement($form->get('communication')); ?>
                    <?= $this->formElementErrors($form->get('communication'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-12 col-md-12 col-lg-12">
                            <?= $this->formLabel($form->get('hasChronicDisease')); ?>
                        </div>
                        <div class="col-sm-2 col-md-2 col-lg-2">
                            <?= $this->formElement($form->get('hasChronicDisease')); ?>
                        </div>
                        <div class="col-sm-10 col-md-10 col-lg-10">
                            <?= $this->formElement($form->get('chronicDisease')); ?>
                            <?= $this->formElementErrors($form->get('chronicDisease'), ['class' => 'alert-danger']); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-12">
                <br>
                <div class="row">
                    <div class="form-group">
                        <div class="col-sm-12 col-md-12 col-lg-12">
                            <?= $this->formLabel($form->get('hasLearningIllness')); ?>
                        </div>
                        <div class="col-sm-2 col-md-2 col-lg-2">
                            <?= $this->formElement($form->get('hasLearningIllness')); ?>
                        </div>
                        <div class="col-sm-10 col-md-10 col-lg-10">
                            <?= $this->formElement($form->get('learningIllness')); ?>
                            <?= $this->formElementErrors($form->get('learningIllness'), ['class' => 'alert-danger']); ?>
                        </div>
                    </div>
                </div>
                <br>
            </div>
            <div class="pull-right">
                <?= $this->formElement($form->get('submit')); ?>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</section>

<script type="text/javascript">
    function validateHasChronicDisease() {
        if ($("[name='hasChronicDisease']").val() == '0') {
            $("[name='chronicDisease']").attr("readonly", "true");
        } else {
            $("[name='chronicDisease']").removeAttr("readonly");
        }
    }
    
    function validateHasLearningIllness() {
        if ($("[name='hasLearningIllness']").val() == '0') {
            $("[name='learningIllness']").attr("readonly", "true");
        } else {
            $("[name='learningIllness']").removeAttr("readonly");
        }
    }
    
    $(document).ready(function () {
        validateHasChronicDisease();
        validateHasLearningIllness();
    });

    $(function () {
        $("[name='hasChronicDisease']").change(function () {
            validateHasChronicDisease();
        });
        $("[name='hasLearningIllness']").change(function () {
            validateHasLearningIllness();
        });
    });
</script>
