<?php
/*
 * Copyright (c) 2017 Elder Mutzus <elmutzus@gmail.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */

?>

<section id="body">
    <div class="text-center"><h3>Evaluaci&oacute;n Demogr&aacute;fica</h3></div>
    <div class="form-small">
        <div class="panel panel-md panel-primary">
            <div class="panel-heading">
                <div class="text-center">
                    Informaci&oacute;n del estudiante - <strong>Gracias por participar</strong>
                </div>                
            </div>
            <div class="panel-body">
                Gracias por actualizar sus datos:
                <br>
                Carn&eacute;: <strong><?= $this->id; ?></strong>
                <br>
                Nombre: <strong><?= $this->fullname; ?></strong>
                <br>
                <br>
                <i>Ya puede cerrar esta p&aacute;gina.</i>
            </div>
        </div>
    </div>
</section>
