<?php
/*
 * Copyright (c) 2017 Elder Mutzus <elmutzus@gmail.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */
$idSecret = urldecode($this->idSecret);
$form->setAttribute('action',  $this->url('surveyManagementRoute', ['action' => 'addOrUpdateStudent', 'id' => $this->id]). '?idSecret=' . urlencode($idSecret));
$form->prepare();
?>

<section id="body">
    <div class="text-center"><h3>Evaluaci&oacute;n Demogr&aacute;fica</h3></div>
    <div class="panel panel-sm panel-primary">
        <div class="panel-heading">
            <div class="text-center">
                <strong>Informaci&oacute;n B&aacute;sica</strong>
            </div>                
        </div>
        <div class="panel-body">
            <?= $this->form()->openTag($form); ?>
            <div class="col-sm-3 col-md-3 col-lg-3">
                <div class="form-group">
                    <?= $this->formLabel($form->get('id')); ?>
                    <?= $this->formElement($form->get('id')); ?>
                    <?= $this->formElementErrors($form->get('id'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-5 col-md-5 col-lg-5">
                <div class="form-group">
                    <?= $this->formLabel($form->get('dpi')); ?>
                    <?= $this->formElement($form->get('dpi')); ?>
                    <?= $this->formElementErrors($form->get('dpi'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <div class="form-group">
                    <?= $this->formLabel($form->get('nov')); ?>
                    <?= $this->formElement($form->get('nov')); ?>
                    <?= $this->formElementErrors($form->get('nov'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-6">
                <div class="form-group">
                    <?= $this->formLabel($form->get('name')); ?>
                    <?= $this->formElement($form->get('name')); ?>
                    <?= $this->formElementErrors($form->get('name'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-6">
                <div class="form-group">
                    <?= $this->formLabel($form->get('lastname')); ?>
                    <?= $this->formElement($form->get('lastname')); ?>
                    <?= $this->formElementErrors($form->get('lastname'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <div class="form-group">
                    <?= $this->formLabel($form->get('gender')); ?>
                    <?= $this->formElement($form->get('gender')); ?>
                    <?= $this->formElementErrors($form->get('gender'), ['class' => 'alert-danger']); ?>
                    <?= $this->formElement($form->get('hiddenGender')); ?>
                </div>
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <div class="form-group">
                    <?= $this->formLabel($form->get('birthdate')); ?>
                    <br>
                    <?= $this->formElement($form->get('birthdate')); ?>
                    <?= $this->formElementErrors($form->get('birthdate'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="form-group">
                    <?= $this->formLabel($form->get('birthplace')); ?>
                    <?= $this->formElement($form->get('birthplace')); ?>
                    <?= $this->formElementErrors($form->get('birthplace'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="pull-right">
                <?= $this->formElement($form->get('submit')); ?>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</section>
