<?php
/*
 * Copyright (c) 2017 Elder Mutzus <elmutzus@gmail.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */
$idSecret = urldecode($this->idSecret);
$form->setAttribute('action', $this->basePath() . $this->url('surveyManagementRoute', ['action' => 'addOrUpdateStudentProfessionalLife', 'id' => $this->id]). '?idSecret=' . urlencode($idSecret));
$form->prepare();
?>

<section id="body">
    <div class="text-center"><h3>Evaluaci&oacute;n Demogr&aacute;fica</h3></div>
    <div class="panel panel-md panel-primary">
        <div class="panel-heading">
            <div class="text-center">
                <strong>Vida profesional</strong>
            </div>                
        </div>
        <div class="panel-body">
            <?= $this->form()->openTag($form); ?>
            <div class="form-group">
                <?= $this->formElement($form->get('studentId')); ?>
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="col-sm-12 col-md-12 col-lg-12">
                        <?= $this->formLabel($form->get('hasScholarship')); ?>
                    </div>
                    <div class="col-sm-2 col-md-2 col-lg-2">
                        <?= $this->formElement($form->get('hasScholarship')); ?>
                    </div>
                    <div class="col-sm-10 col-md-10 col-lg-10">
                        <?= $this->formElement($form->get('scholarship')); ?>
                        <?= $this->formElementErrors($form->get('scholarship'), ['class' => 'alert-danger']); ?>
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-sm-3 col-md-3 col-lg-3">
                    <div class="form-group">
                        <?= $this->formLabel($form->get('studiesLanguages')); ?>
                        <?= $this->formElement($form->get('studiesLanguages')); ?>
                        <?= $this->formElementErrors($form->get('studiesLanguages'), ['class' => 'alert-danger']); ?>
                    </div>
                </div>
                <div class="col-sm-3 col-md-3 col-lg-3">
                    <div class="form-group">
                        <?= $this->formLabel($form->get('studiesLanguagesPercentage')); ?>
                        <?= $this->formElement($form->get('studiesLanguagesPercentage')); ?>
                        <?= $this->formElementErrors($form->get('studiesLanguagesPercentage'), ['class' => 'alert-danger']); ?>
                    </div>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-6">
                    <div class="form-group">
                        <?= $this->formLabel($form->get('studiesWhichLanguages')); ?>
                        <?= $this->formElement($form->get('studiesWhichLanguages')); ?>
                        <?= $this->formElementErrors($form->get('studiesWhichLanguages'), ['class' => 'alert-danger']); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3 col-md-3 col-lg-3">
                    <div class="form-group">
                        <?= $this->formLabel($form->get('handlesLanguages')); ?>
                        <?= $this->formElement($form->get('handlesLanguages')); ?>
                        <?= $this->formElementErrors($form->get('handlesLanguages'), ['class' => 'alert-danger']); ?>
                    </div>
                </div>
                <div class="col-sm-3 col-md-3 col-lg-3">
                    <div class="form-group">
                        <?= $this->formLabel($form->get('handlesLanguagesPercentage')); ?>
                        <?= $this->formElement($form->get('handlesLanguagesPercentage')); ?>
                        <?= $this->formElementErrors($form->get('handlesLanguagesPercentage'), ['class' => 'alert-danger']); ?>
                    </div>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-6">
                    <div class="form-group">
                        <?= $this->formLabel($form->get('handlesWhichLanguages')); ?>
                        <?= $this->formElement($form->get('handlesWhichLanguages')); ?>
                        <?= $this->formElementErrors($form->get('handlesWhichLanguages'), ['class' => 'alert-danger']); ?>
                    </div>
                </div>                
            </div>
            <div class="form-group">
                <?= $this->formLabel($form->get('careerId')); ?>
                <?= $this->formElement($form->get('careerId')); ?>
                <?= $this->formElementErrors($form->get('careerId'), ['class' => 'alert-danger']); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('careerMotivation')); ?>
                <?= $this->formElement($form->get('careerMotivation')); ?>
                <?= $this->formElementErrors($form->get('careerMotivation'), ['class' => 'alert-danger']); ?>
            </div>
            <div class="form-group">
                <?= $this->formLabel($form->get('hobbies')); ?>
                <?= $this->formElement($form->get('hobbies')); ?>
                <?= $this->formElementErrors($form->get('hobbies'), ['class' => 'alert-danger']); ?>
            </div>
            <div class="form-group">
                <?= $this->formLabel($form->get('selfDescription')); ?>
                <?= $this->formElement($form->get('selfDescription')); ?>
                <?= $this->formElementErrors($form->get('selfDescription'), ['class' => 'alert-danger']); ?>
            </div>


            <div class="pull-right">
                <?= $this->formElement($form->get('submit')); ?>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</section>

<script type="text/javascript">

    function validateHasSholarship() {
        if ($("[name='hasScholarship']").val() == '0') {
            $("[name='scholarship']").attr("readonly", "true");
        } else {
            $("[name='scholarship']").removeAttr("readonly");
        }
    }
    
    function validateStudiesLanguages() {
        if ($("[name='studiesLanguages']").val() == '0') {
            $("[name='studiesLanguagesPercentage']").attr("readonly", "true");
            $("[name='studiesWhichLanguages']").attr("readonly", "true");
        } else {
            $("[name='studiesLanguagesPercentage']").removeAttr("readonly");
            $("[name='studiesWhichLanguages']").removeAttr("readonly");
        }
    }
    
    function validateHandlesLanguages() {
        if ($("[name='handlesLanguages']").val() == '0') {
            $("[name='handlesLanguagesPercentage']").attr("readonly", "true");
            $("[name='handlesWhichLanguages']").attr("readonly", "true");
        } else {
            $("[name='handlesLanguagesPercentage']").removeAttr("readonly");
            $("[name='handlesWhichLanguages']").removeAttr("readonly");
        }
    }

    $(document).ready(function () {
        validateHasSholarship();
        validateStudiesLanguages();
        validateHandlesLanguages();
    });

    $(function () {
        $("[name='hasScholarship']").change(function () {
            validateHasSholarship();
        });
        $("[name='studiesLanguages']").change(function () {
            validateStudiesLanguages();
        });
        $("[name='handlesLanguages']").change(function () {
            validateHandlesLanguages();
        });
    });
</script>