<?php

/* 
 * Copyright (c) 2017 Elder Mutzus <elmutzus@gmail.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */

$url = $this->basePath() . $this->url('roleManagementRoute', ['action' => 'delete', 'id' => $id]);
?>

<section id="body">
    <div class="text-center"><h3>Gesti&oacute;n de roles</h3></div>
    <div class="form-small">
        <div class="panel panel-sm panel-primary">
            <div class="panel-heading">
                <div class="text-center">
                    Eliminación de Rol
                </div>                
            </div>
            <div class="panel-body">
                <p>
                    Esta seguro de eliminar el rol "<?= $this->escapeHtml($id) ?>"?
                </p>
            </div>
            <div class="panel-footer">
                <form action="<?= $url ?>" method="post">
                    <div class="form-group">
                        <input type="hidden" name="id" value="<?= $id ?>" />
                        <input type="submit" class="btn btn-danger" name="del" value="Si" />
                        <input type="submit" class="btn btn-success" name="del" value="No" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>