<?php

/* 
 * Copyright (c) 2017 Elder Mutzus <elmutzus@gmail.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */

$form->setAttribute('action', $this->url('roleManagementRoute', ['action' => 'modify', 'id' => $this->form->get('id')->getValue()]));
$form->prepare();
?>

<section id="body">
    <div class="text-center"><h3>Gesti&oacute;n de roles</h3></div>
    <div class="form-small">
        <div class="panel panel-sm panel-primary">
            <div class="panel-heading">
                <div class="text-center">
                    Modificación de Rol
                </div>                
            </div>
            <div class="panel-body">
                <?= $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?= $this->formLabel($form->get('id')); ?>
                    <?= $this->formElement($form->get('id')); ?>
                    <?= $this->formElementErrors($form->get('id'), ['class' => 'alert-danger']); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('description')); ?>
                    <?= $this->formElement($form->get('description')); ?>
                    <?= $this->formElementErrors($form->get('description'), ['class' => 'alert-danger']); ?>
                </div>
                <?= $this->formElement($form->get('submit')); ?>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</section>
