<?php
/*
 * Copyright (c) 2017 Elder Mutzus <elmutzus@gmail.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */

$items = $this->items;
?>

<section id="body">
    <div class="text-center"><h3>Gesti&oacute;n de p&aacute;ginas</h3></div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            Listado de P&aacute;ginas
        </div>
        <div class="panel-body">
            <?php echo $this->partial('partial-view/page-table', ['items' => $items]); ?>
        </div>
        <div class="panel-footer">
            <a class="btn btn-primary btn-sm" href="<?= $this->basePath() . $this->url('pageManagementRoute', ['action' => 'add', 'id' => 'newItem']) ?>">
                Agregar nueva
            </a>
        </div>
    </div>
    <div class="row">
        <div class="pull-right">
            <?=
            $this->paginationControl($items, 'Sliding', 'partial-view/paginator', ['route' => 'pageManagementRoute']);
            ?>
        </div>
    </div>
</section>