<?php
/*
 * Copyright (c) 2017 Elder Mutzus <elmutzus@gmail.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */
?>
<div class="table-responsive">
    <table class="table table-hover table-striped table-condensed">
        <thead>
            <tr>
                <th>Carn&eacute;</th>
                <th>N.O.V.</th>
                <th>Nombre</th>
                <th>Prom. Anterior</th>
                <th>Prom. Actual</th>
                <th>Resultado</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php
            if ($this->rows != null)
            {
                $limit = sizeof($this->rows);

                for ($i = 0; $i < $limit; $i ++)
                {
                    $actualData = $this->rows[$i];
                    $prevData   = $this->rows[$i + 1];

                    if ($prevData['student'] == $actualData['student'])
                    {
                        echo $this->partial('partial-view/report1-row', ['latestRow' => $actualData, 'previousAvg' => $prevData['average']]);
                        $i++;
                    }
                    else
                    {
                        echo $this->partial('partial-view/report1-row', ['latestRow' => $actualData, 'previousAvg' => 0]);
                    }
                }
            }
            ?>  
        </tbody>
    </table>
</div>