<?php

/* 
 * Copyright (c) 2017 Elder Mutzus <elmutzus@gmail.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */

?>
            
<tr>
    <td> <?= $this->latestRow['student'] ?> </td>
    <td> <?= $this->latestRow['vocational_id'] ?> </td>
    <td> <?= $this->latestRow['name'] ?> </td>
    <td> <?= $this->latestRow['average'] ?> </td>
    <td> <?= $this->latestRow['average'] ?> </td>
    <td> 5% </td>
    <td>         
        <a class="btn btn-primary btn-xs" href="">
            Detalle
        </a>
    </td>
</tr>