<?php

/* 
 * Copyright (c) 2017 Elder Mutzus <elmutzus@gmail.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */

?>
<div class="table-responsive">
    <table class="table table-hover table-striped table-condensed" id="paginatedTable">
        <thead>
            <tr>
                <th>Carn&eacute;</th>
                <th>N.O.V.</th>
                <th>C.U.I.</th>
                <th>Nombre</th>
                <th>Promedio</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php
            if ($this->rows != null)
            {
                foreach ($this->rows as $row)
                {
                    echo $this->partial('partial-view/report3-row', ['row' => $row]);
                }
            }
            ?>  
        </tbody>
    </table>
</div>
<script type="text/javascript">
    $('#paginatedTable').each(function () {
        var currentPage = 0;
        var numPerPage = 30;
        var $table = $(this);
        
        $table.bind('repaginate', function () {
            $table.find('tbody tr').hide().slice(currentPage * numPerPage, (currentPage + 1) * numPerPage).show();
        });
        
        $table.trigger('repaginate');
        
        var numRows = $table.find('tbody tr').length;
        var numPages = Math.ceil(numRows / numPerPage);
        var $pager = $('<div class="pager"></div>');
        
        for (var page = 0; page < numPages; page++) {
            $('<button class="btn btn-primary btn-sm"></btn>').text(page + 1).bind('click', {
                newPage: page
            }, function (event) {
                currentPage = event.data['newPage'];
                $table.trigger('repaginate');
                $(this).addClass('active').siblings().removeClass('active');
            }).appendTo($pager).addClass('clickable');
        }
        
        $pager.insertAfter($table).find('button.btn:first').addClass('active');
    });
</script>