<?php

/* 
 * Copyright (c) 2017 Elder Mutzus <elmutzus@gmail.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */

?>

<div class="panel panel-md panel-primary">
    <div class="panel-heading">
        Detalle Reporte 3 - "Proyección del rendimiento del estudiante"
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-4 col-md-4 col-lg-4">
                <div class="form-group">
                    <label for="studentId" class="control-label">Carn&eacute;</label>
                    <input id="studentId" name="studentId" class="form-control" type="number" value="<?= $this->studentId; ?>" disabled="true" />
                </div>
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <div class="form-group">
                    <label for="studentName" class="control-label">Nombre</label>
                    <input type="text" class="form-control" id="studentName" name="studentName" value="<?= $this->studentName; ?>" disabled="true" />
                </div>
            </div>
        </div>
        <div class="row">
            <div id="chart_div" class="chart"></div>
        </div>     
    </div>
</div>

<script type="text/javascript">
    // Load the Visualization API and the corechart package.
    google.charts.load("visualization", "1", {packages: ["corechart", "line"]});

    // Set a callback to run when the Google Visualization API is loaded.
    google.charts.setOnLoadCallback(drawChart);

    // Callback that creates and populates a data table,
    // instantiates the pie chart, passes in the data and
    // draws it.
    function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('number', 'Año');
        data.addColumn('number', 'Nota');

<?php
if ($this->reportDetail != null && sizeof($this->reportDetail) > 0)
{
    ?>
            data.addRows([
    <?php
    $limit = sizeof($this->reportDetail);

    for ($i = 0; $i < $limit; $i++)
    {
        $row = $this->reportDetail[$i];

        echo('[' . (float)$row['period'] . ',' . $row['note'] . ']');

        if ($i != ($limit - 1))
        {
            echo(',');
        }
    }
    ?>
            ]);

    <?php
}
?>

        // Set chart options
        var options = {
            title: 'Historial de notas',
            hAxis: {title: 'Año'},
            vAxis: {title: 'Nota', minValue: 0, maxValue: 100},
            legend: 'bottom',
            displayAnnotations: true,
            trendlines: {
                0: {
                    color: 'red',
                    opacity: 0.3,
                    visibleInLegend: true,
                    pointsVisible: true
                }
            }
        };

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.ScatterChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }

    $(window).resize(function () {
        drawChart();
    });
</script>