<?php
/*
 * Copyright (c) 2017 Elder Mutzus <elmutzus@gmail.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */

$form->setAttribute('action', $this->url('reportsManagementRoute', ['action' => 'report1']));
$form->prepare();
?>

<section id="body">
    <div class="text-center"><h3>Reporte 1</h3> <strong>"Comparativo del promedio de notas Vs. un valor anterior"</strong></div>

    <div class="row">
        <?= $this->form()->openTag($form); ?>

        <div id="searchUsingCareers" name="searchUsingCareers" class="col-sm-10 col-md-10 col-lg-10">
            <div class="col-sm-8 col-md-8 col-lg-8">
                <div class="form-group">
                    <?= $this->formLabel($form->get('career')); ?>
                    <?= $this->formElement($form->get('career')); ?>
                    <?= $this->formElementErrors($form->get('career'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <div class="form-group">
                    <?= $this->formLabel($form->get('year')); ?>
                    <?= $this->formElement($form->get('year')); ?>
                    <?= $this->formElementErrors($form->get('year'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <div class="form-group">
                    <?= $this->formLabel($form->get('course')); ?>
                    <?= $this->formElement($form->get('course')); ?>
                    <?= $this->formElementErrors($form->get('course'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <div class="form-group">
                    <?= $this->formLabel($form->get('semester')); ?>
                    <?= $this->formElement($form->get('semester')); ?>
                    <?= $this->formElementErrors($form->get('semester'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
        </div>
        <div id="searchUsingStudents" name="searchUsingStudents" class="col-sm-10 col-md-10 col-lg-10">
            <div class="col-sm-4 col-md-4 col-lg-4">
                <div class="form-group">
                    <?= $this->formLabel($form->get('dpi')); ?>
                    <?= $this->formElement($form->get('dpi')); ?>
                    <?= $this->formElementErrors($form->get('dpi'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <div class="form-group">
                    <?= $this->formLabel($form->get('name')); ?>
                    <?= $this->formElement($form->get('name')); ?>
                    <?= $this->formElementErrors($form->get('name'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <div class="form-group">
                    <?= $this->formLabel($form->get('nov')); ?>
                    <?= $this->formElement($form->get('nov')); ?>
                    <?= $this->formElementErrors($form->get('nov'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <div class="form-group">
                    <?= $this->formLabel($form->get('lastname')); ?>
                    <?= $this->formElement($form->get('lastname')); ?>
                    <?= $this->formElementErrors($form->get('lastname'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
        </div>
        <div id="searcheableControls" name="searcheableControls" class="col-sm-2 col-md-2 col-lg-2">
            <div id="searcheableFilter" class="form-group">
                <div class="form-group">
                    <?= $this->formLabel($form->get('filterBy')); ?>
                    <?= $this->formElement($form->get('filterBy')); ?>
                    <?= $this->formElementErrors($form->get('filterBy'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="form-group">
                <label>&nbsp;</label>
                <?= $this->formElement($form->get('submit')); ?>
            </div>
        </div>

        <?= $this->form()->closeTag(); ?>
    </div>
    <div class="panel panel-md panel-primary">
        <div class="panel-heading">
            Listado de Estudiantes
        </div>
        <div class="panel-body">
            <?php echo $this->partial('partial-view/report1-table', ['rows' => $this->reportData]); ?>
        </div>
    </div>
    <div>
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" data-focus-on="input:first" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">Detalle del estudiante</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-sm-4 col-md-4 col-lg-4">
                                <div class="form-group">
                                    <label for="identification" class="control-label">Carn&eacute;</label>
                                    <input id="identification" name="identification" class="form-control" type="number" value="201212345" disabled="true" />
                                </div>
                            </div>
                            <div class="col-sm-8 col-md-8 col-lg-8">
                                <div class="form-group">
                                    <label for="name" class="control-label">Nombre</label>
                                    <input type="text" class="form-control" id="name" name="name" value="Lorem Ipsum Sit Amet" disabled="true" />
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group">
                                    <label class="control-label">Posibles razones</label>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" class="checkbox-inline" value="">El lugar de residencia es mas lejano
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" class="checkbox-inline" value="">Actualmente trabaja
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" class="checkbox-inline" value="">Estado civil soltero
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" class="checkbox-inline" value="">Actualmente tiene hijos
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" class="checkbox-inline" value="">La cantidad de cursos es mayor al semestre anterior
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-12">
                                <div id="chart_div" class="chart"></div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <a href="javascript:getCurrentUrl();" class="btn btn-success pull-left">
                            Ver perfil
                        </a>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">

    function showSearchFilters() {
        if ($("[name='filterBy']").val() == 'S') {
            $("[name='searchUsingStudents']").show();
            $("[name='searchUsingCareers']").hide();
        } else {
            $("[name='searchUsingStudents']").hide();
            $("[name='searchUsingCareers']").show();
        }
    }

    $(document).ready(function () {
        showSearchFilters();
    });

    $(function () {
        $("[name='filterBy']").change(function () {
            showSearchFilters();
        });
    });

</script>

<script type="text/javascript">
    // Load the Visualization API and the corechart package.
    google.charts.load("visualization", "1", {packages:["corechart"]});

    // Set a callback to run when the Google Visualization API is loaded.
    google.charts.setOnLoadCallback(drawChart);

    // Callback that creates and populates a data table,
    // instantiates the pie chart, passes in the data and
    // draws it.
    function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Nota');
        data.addColumn('number', 'Nota');
        data.addRows([
            ['Anterior', 90],
            ['Actual', 85]
            ]);

        // Set chart options
        var options = {
            title: 'Comparativo de notas',
            hAxis: { title: 'Notas' }
        };

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }

    $(window).resize(function(){
        drawChart();
    });
</script>