<?php
/*
 * Copyright (c) 2017 Elder Mutzus <elmutzus@gmail.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */

$form->setAttribute('action', $this->url('reportsManagementRoute', ['action' => 'report2']));
$form->prepare();
?>

<section id="body">
    <div class="text-center"><h3>Reporte 2</h3> <strong>"Histórico"</strong></div>

    <div class="row">
        <?= $this->form()->openTag($form); ?>

        <div id="searchUsingCareers" name="searchUsingCareers" class="col-sm-10 col-md-10 col-lg-10">
            <div class="col-sm-8 col-md-8 col-lg-8">
                <div class="form-group">
                    <?= $this->formLabel($form->get('career')); ?>
                    <?= $this->formElement($form->get('career')); ?>
                    <?= $this->formElementErrors($form->get('career'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <div class="form-group">
                    <?= $this->formLabel($form->get('year')); ?>
                    <?= $this->formElement($form->get('year')); ?>
                    <?= $this->formElementErrors($form->get('year'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <div class="form-group">
                    <?= $this->formLabel($form->get('course')); ?>
                    <?= $this->formElement($form->get('course')); ?>
                    <?= $this->formElementErrors($form->get('course'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <div class="form-group">
                    <?= $this->formLabel($form->get('semester')); ?>
                    <?= $this->formElement($form->get('semester')); ?>
                    <?= $this->formElementErrors($form->get('semester'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
        </div>
        <div id="searchUsingStudents" name="searchUsingStudents" class="col-sm-10 col-md-10 col-lg-10">
            <div class="col-sm-4 col-md-4 col-lg-4">
                <div class="form-group">
                    <?= $this->formLabel($form->get('dpi')); ?>
                    <?= $this->formElement($form->get('dpi')); ?>
                    <?= $this->formElementErrors($form->get('dpi'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <div class="form-group">
                    <?= $this->formLabel($form->get('name')); ?>
                    <?= $this->formElement($form->get('name')); ?>
                    <?= $this->formElementErrors($form->get('name'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <div class="form-group">
                    <?= $this->formLabel($form->get('nov')); ?>
                    <?= $this->formElement($form->get('nov')); ?>
                    <?= $this->formElementErrors($form->get('nov'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <div class="form-group">
                    <?= $this->formLabel($form->get('lastname')); ?>
                    <?= $this->formElement($form->get('lastname')); ?>
                    <?= $this->formElementErrors($form->get('lastname'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
        </div>
        <div id="searcheableControls" name="searcheableControls" class="col-sm-2 col-md-2 col-lg-2">
            <div id="searcheableFilter" class="form-group">
                <div class="form-group">
                    <?= $this->formLabel($form->get('filterBy')); ?>
                    <?= $this->formElement($form->get('filterBy')); ?>
                    <?= $this->formElementErrors($form->get('filterBy'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="form-group">
                <label>&nbsp;</label>
                <?= $this->formElement($form->get('submit')); ?>
            </div>
        </div>

        <?= $this->form()->closeTag(); ?>
    </div>
    <div class="panel panel-md panel-primary">
        <div class="panel-heading">
            Listado de Estudiantes
        </div>
        <div class="panel-body">
            <?php echo $this->partial('partial-view/report2-table', ['rows' => $this->reportData]); ?>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-12">

                    <div class="pull-right">
                        <a id="exportReportBtn" class="btn btn-success btn-sm" target="_blank">Exportar a Excel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">

    function showSearchFilters() {
        if ($("[name='filterBy']").val() == 'S') {
            $("[name='searchUsingStudents']").show();
            $("[name='searchUsingCareers']").hide();
        } else {
            $("[name='searchUsingStudents']").hide();
            $("[name='searchUsingCareers']").show();
        }
    }

    $(document).ready(function () {
        showSearchFilters();

        document.getElementById("exportReportBtn").onclick = function () {
            window.open("reportExport?rpt=2"
                    + "&crr=" + $("[name='career']").val()
                    + "&yr=" + $("[name='year']").val()
                    + "&crs=" + $("[name='course']").val()
                    + "&smstr=" + $("[name='semester']").val()
                    + "&dp=" + $("[name='dpi']").val()
                    + "&nv=" + $("[name='nov']").val()
                    + "&nm=" + $("[name='name']").val()
                    + "&lstnm=" + $("[name='lastname']").val()
                    + "&fltrby=" + $("[name='filterBy']").val(),
                    "_blank");
        };
    });

    $(function () {
        $("[name='filterBy']").change(function () {
            showSearchFilters();
        });
    });

</script>