<?php
/*
 * Copyright (c) 2017 Elder Mutzus <elmutzus@gmail.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */

$form->setAttribute('action', $this->basePath() . $this->url('reportsManagementRoute', ['action' => 'report5']));
$form->prepare();
?>

<section id="body">
    <div class="text-center"><h3>Reporte 5</h3> <strong>"Top de notas de estudiantes por curso" </strong></div>

    <div class="row">
        <?= $this->form()->openTag($form); ?>

        <div id="searchUsingCareers" name="searchUsingCareers" class="col-sm-10 col-md-10 col-lg-10">
            <div class="col-sm-8 col-md-8 col-lg-8">
                <div class="form-group">
                    <?= $this->formLabel($form->get('career')); ?>
                    <?= $this->formElement($form->get('career')); ?>
                    <?= $this->formElementErrors($form->get('career'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <div class="form-group">
                    <?= $this->formLabel($form->get('year')); ?>
                    <?= $this->formElement($form->get('year')); ?>
                    <?= $this->formElementErrors($form->get('year'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <div class="form-group">
                    <?= $this->formLabel($form->get('course')); ?>
                    <?= $this->formElement($form->get('course')); ?>
                    <?= $this->formElementErrors($form->get('course'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <div class="form-group">
                    <?= $this->formLabel($form->get('semester')); ?>
                    <?= $this->formElement($form->get('semester')); ?>
                    <?= $this->formElementErrors($form->get('semester'), ['class' => 'alert-danger']); ?>
                </div>
            </div>
        </div>
        <div id="searcheableControls" name="searcheableControls" class="col-sm-2 col-md-2 col-lg-2">
            <div class="form-group">
                <label>&nbsp;</label>
                <?= $this->formElement($form->get('submit')); ?>
            </div>
        </div>

        <?= $this->form()->closeTag(); ?>
    </div>
    <div class="panel panel-md panel-primary">
        <div class="panel-heading">
            Listado de Estudiantes
        </div>
        <div class="panel-body">
            <?php echo $this->partial('partial-view/report5-table', ['rows' => $this->reportData]); ?>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-12">

                    <div class="pull-right">
                        <a id="exportReportBtn" class="btn btn-success btn-sm" target="_blank">Exportar a Excel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">

    $(document).ready(function () {
        document.getElementById("exportReportBtn").onclick = function () {
            window.open("reportExport?rpt=5"
                    + "&crr=" + $("[name='career']").val()
                    + "&yr=" + $("[name='year']").val()
                    + "&crs=" + $("[name='course']").val()
                    + "&smstr=" + $("[name='semester']").val(),
                    "_blank");
        };
    });

</script>