<?php

/* 
 * Copyright (c) 2017 Elder Mutzus <elder.mutzus@inspireswgt.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elder.mutzus@inspireswgt.com> - initial API and implementation and/or initial documentation
 */

$comopsedKey = $this->item['page'] . '-' . $this->item['role']
?>

<tr>
    <td> <?= $this->item['page'] ?> </td>
    <td> <?= $this->item['role'] ?> </td>
    <td> <?= $this->item['description'] ?> </td>
    <td>         
        <a class="btn btn-danger btn-xs" href="<?=  $this->url('pagePerRoleManagementRoute', ['action' => 'delete', 'id' => $comopsedKey]) ?>">
            Eliminar
        </a>
    </td>
</tr>