<?php

/* 
 * Copyright (c) 2017 Elder Mutzus <elmutzus@gmail.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */
?>

<table class="table table-hover table-striped table-condensed">
    <thead>
        <tr>
            <th>Rol</th>
            <th>Descripci&oacute;n</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($this->items as $item)
        {
            echo $this->partial('partial-view/role-row', ['item' => $item]);
        }
        ?>    
    </tbody>
</table>
