<?php

/* 
 * Copyright (c) 2017 Elder Mutzus <elmutzus@gmail.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */

$comopsedKey = $this->item['role'] . '-' . $this->item['user']
?>

<tr>
    <td> <?= $this->item['role'] ?> </td>
    <td> <?= $this->item['user'] ?> </td>
    <td> <?= $this->item['description'] ?> </td>
    <td>         
        <a class="btn btn-danger btn-xs" href="<?= $this->basePath() . $this->url('rolePerUserManagementRoute', ['action' => 'delete', 'id' => $comopsedKey]) ?>">
            Eliminar
        </a>
    </td>
</tr>