<?php
/*
 * Copyright (c) 2017 Elder Mutzus <elder.mutzus@inspireswgt.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elder.mutzus@inspireswgt.com> - initial API and implementation and/or initial documentation
 */
?>

<tr>
    <td> <?= $this->user['user'] ?> </td>
    <td> <?= $this->user['name'] ?> </td>
    <td> <?= $this->user['lastname'] ?> </td>
    <td> <?= $this->user['email'] ?> </td>
    <td> <?= $this->user['phone'] ?> </td>
    <td>         
        <a class="btn btn-primary btn-xs" href="<?= $this->url('userManagementRoute', ['action' => 'modify', 'user' => $this->user['user']]) ?>">
            Modificar
        </a>
        <a class="btn btn-danger btn-xs" href="<?= $this->url('userManagementRoute', ['action' => 'delete', 'user' => $this->user['user']]) ?>">
            Eliminar
        </a>
    </td>
</tr>