<?php
/*
 * Copyright (c) 2017 Elder Mutzus <elmutzus@gmail.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */

$this->doctype();
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('SEMDE - Platform')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/eps-development.css'))
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
                ->prependFile($this->basePath('js/chartloader.js'))
        ?>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-fixed-top">
                <div class="navbar-header">
                    <button type="button" class="btn btn-success navbar-toggle" data-toggle="collapse" data-target="#collapseable-nav">
                        <span class="glyphicon glyphicon-chevron-down"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('mainDashboardRoute') ?>">
                        SEMDE
                    </a> 
                </div>
                <div class="navbar-collapse collapse" id="collapseable-nav">
                    <ul class="nav navbar-nav">
                        <?php if (sizeof($reportPages) > 0): ?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-stats"></span> Reportes <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <?php foreach ($reportPages as $key => $val): ?>
                                        <li>
                                            <a href="<?php echo($val) ?>"><?php echo($key) ?></a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </li> 
                        <?php endif; ?>
                        <?php if (sizeof($managementPages) > 0): ?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span> Configuraciones <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <?php foreach ($managementPages as $key => $val): ?>
                                        <li>
                                            <a href="<?php echo($val) ?>"><?php echo($key) ?></a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </li>
                        <?php endif; ?>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-user"></span>&nbsp; <?= $this->currentUser ?>
                                <span class="caret"></span>                          
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li class="disabled">
                                    <a href="#"><span class="glyphicon glyphicon-lock"></span> Rol: <?= $this->currentUserRole ?></a>
                                </li>
                                <li class="divider"></li>
                                <li class="disabled">
                                    <a href="#"><span class="glyphicon glyphicon-refresh"></span> v.<?= \Core\Module::VERSION ?></a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="<?= $this->url('logoutRoute') ?>"><span class="glyphicon glyphicon-off"></span> Cerrar sesi&oacute;n</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2016 - <?= date('Y') ?> by FARUSAC. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
