<?php
/*
 * Copyright (c) 2017 Elder Mutzus <elmutzus@inspireswgt.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */

$form = $this->form;
$form->prepare();
?>

<section id="body">
    <div class="text-center"><h3>Bienvenido a la Plataforma de Seguimiento al Estudiante</h3></div>
    <div class="form-small">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Inicio de sesi&oacute;n
            </div>
            <div class="panel-body">
                <?= $this->form()->openTag($form); ?>                
                <div class="form-group">
                    <?= $this->formLabel($form->get('id')); ?>
                    <?= $this->formElement($form->get('id')); ?>
                    <?= $this->formElementErrors($form->get('id'), ['class' => 'alert-danger']); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('password')); ?>
                    <?= $this->formElement($form->get('password')); ?>
                    <?= $this->formElementErrors($form->get('password'), ['class' => 'alert-danger']); ?>
                </div>  
                <div class="checkbox">
                    <label>
                         <?=$this->formElement($form->get('rememberMe')); ?> Recordarme
                    </label>
                </div>
                <?= $this->formElement($form->get('submit')); ?>
                <?= $this->form()->closeTag(); ?>
                <br>
                <?php if ($isLoginError): ?>
                    <div class="alert alert-danger" role="alert">
                        Usuario y/o contrase&ntilde;a incorrectos.
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>
