<?php

/* 
 * Copyright (c) 2017 Elder Mutzus <elmutzus@gmail.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */


?>

<section id="body">
    <div class="text-center"><h3>Bienvenido a Plataforma de Seguimiento al Estudiante</h3></div>
    
    <h3><i>Sems sde</i></h3>
    
    En lengua Wylie, se traduce como <i>Divis&oacute;n de mente</i>, uno de los tres pilares dentro de Atiyoga para alcanzar la <b>Gran Perfecci&oacute;n de la Mente</b>.
</section>