<?php

/* 
 * Copyright (c) 2017 Elder Mutzus <elder.mutzus@inspireswgt.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elder.mutzus@inspireswgt.com> - initial API and implementation and/or initial documentation
 */

$form = $this->form;
$form->prepare();
?>

<section id="body">
    <div class="text-center"><h3>Bienvenido a Plataforma de Seguimiento al Estudiante</h3></div>
    <div class="form-small">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Inicio de sesi&oacute;n
            </div>
            <div class="panel-body">
                <?= $this->form()->openTag($form); ?>                
                <div class="form-group">
                    <?= $this->formLabel($form->get('user')); ?>
                    <?= $this->formElement($form->get('user')); ?>
                    <?= $this->formElementErrors($form->get('user'), ['class' => 'alert-danger']); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('availableRoles')); ?>
                    <?= $this->formElement($form->get('availableRoles')); ?>
                    <?= $this->formElementErrors($form->get('availableRoles'), ['class' => 'alert-danger']); ?>
                </div>  
                <?= $this->formElement($form->get('submit')); ?>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</section>