<?php
/*
 * Copyright (c) 2017 Elder Mutzus <elmutzus@inspireswgt.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elder.mutzus@inspireswgt.com> - initial API and implementation and/or initial documentation
 */


?>

<section id="body">
    <div class="text-center"><h3>Gestión de usuarios</h3></div>
    <div class="form-small">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Usuarios
            </div>
            <div class="panel-body">
                Body
            </div>
        </div>
    </div>
</section>
