<?php
/*
 * Copyright (c) 2017 Elder Mutzus <elmutzus@inspireswgt.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elmutzus@gmail.com> - initial API and implementation and/or initial documentation
 */

$users = $this->users;
?>

<section id="body">
    <div class="text-center"><h3>Gesti&oacute;n de usuarios</h3></div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            Listado de Usuarios
        </div>
        <div class="panel-body">
            <?php echo $this->partial('partial-view/user-table', ['users' => $users]); ?>
        </div>
        <div class="panel-footer">
            <a class="btn btn-primary btn-sm" href="<?=  $this->url('userManagementRoute', ['action' => 'add', 'id' => 'newItem']) ?>">
                Agregar nuevo
            </a>
        </div>
    </div>
    <div class="row">
        <div class="pull-right">
            <?=
            $this->paginationControl($users, 'Sliding', 'partial-view/paginator', ['route' => 'userManagementRoute']);
            ?>
        </div>
    </div>
</section>
