<?php

/* 
 * Copyright (c) 2017 Elder Mutzus <elder.mutzus@inspireswgt.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Elder Mutzus <elder.mutzus@inspireswgt.com> - initial API and implementation and/or initial documentation
 */
$form->setAttribute('action', $this->url('userManagementRoute', ['action' => 'modify', 'user' => $this->form->get('user')->getValue()]));
$form->prepare();
?>

<section id="body">
    <div class="text-center"><h3>Gesti&oacute;n de usuarios</h3></div>
    <div class="form-small">
        <div class="panel panel-sm panel-primary">
            <div class="panel-heading">
                <div class="text-center">
                    Modificación de Usuario
                </div>                
            </div>
            <div class="panel-body">
                <?= $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?= $this->formLabel($form->get('user')); ?>
                    <?= $this->formElement($form->get('user')); ?>
                    <?= $this->formElementErrors($form->get('user'), ['class' => 'alert-danger']); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('password')); ?>
                    <?= $this->formElement($form->get('password')); ?>
                    <?= $this->formElementErrors($form->get('password'), ['class' => 'alert-danger']); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('name')); ?>
                    <?= $this->formElement($form->get('name')); ?>
                    <?= $this->formElementErrors($form->get('name'), ['class' => 'alert-danger']); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('lastname')); ?>
                    <?= $this->formElement($form->get('lastname')); ?>
                    <?= $this->formElementErrors($form->get('lastname'), ['class' => 'alert-danger']); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('email')); ?>
                    <?= $this->formElement($form->get('email')); ?>
                    <?= $this->formElementErrors($form->get('email'), ['class' => 'alert-danger']); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('phone')); ?>
                    <?= $this->formElement($form->get('phone')); ?>
                    <?= $this->formElementErrors($form->get('phone'), ['class' => 'alert-danger']); ?>
                </div>
                <?= $this->formElement($form->get('submit')); ?>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</section>
